services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432

