# Generated by Django 5.2.4 on 2025-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название клиники')),
                ('booking_url', models.URLField(help_text='https://ya.ru', verbose_name='Ссылка для записи')),
                ('maps_app_url', models.CharField(help_text='https://ya.ru', verbose_name='Ссылка для Яндекс.Картах')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['name'],
            },
        ),
    ]
